apiversion: v2
name: onecx-parameter
version: 0.0.0
appversion: 0.0.0
dependencies:
- name: helm-product
  version: 0.4.0
  repository: oci://ghcr.io/onecx/charts
  alias: product
- name: onecx-parameter-svc
  version: "1.6.0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.svc"
  alias: "svc"
- name: onecx-parameter-bff
  version: "1.5.0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.bff"
  alias: "bff"
- name: onecx-parameter-ui
  version: "1.7.0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.ui"
  alias: "ui"
- name: onecx-parameter-operator
  version: "1.6.*"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.operator"
  alias: "operator"
